name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install
        playwright install-deps
        pip install opencv-python-headless
        pip install -r requirements.txt

#    -
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v3
#    -
#      name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: rocaelfaller/private-flask-media-crawler:latest

        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to personal server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull rocaelfaller/private-flask-media-crawler:latest
          docker stop flaskapi || true
          docker rm flaskapi || true
          docker run -d --name flaskapi -p 37000:5000 rocaelfaller/private-flask-media-crawler:latest