name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        echo Username: ${{ secrets.DOCKER_HUB_USERNAME }}
        python -m pip install --upgrade pip
        pip install opencv-python-headless
        pip install -r requirements.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rocaelfaller/private-flask-media-crawler:latest

    - name: Deploy to personal server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull rocaelfaller/private-flaskapi:latest
          docker stop flaskapi || true
          docker rm flaskapi || true
          docker run -d --name flaskapi -p 37000:5000 rocaelfaller/private-flaskapi:latest